name: Daily LinkedIn Post

on:
  schedule:
    # Runs every day at 06:00 UTC; adjust as needed.
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run LinkedIn bot
        env:
          LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
          LINKEDIN_OWNER_URN: ${{ secrets.LINKEDIN_OWNER_URN }}

          # Optional overrides – define these secrets only if you need them.
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
          TOPIC: ${{ secrets.TOPIC }}
        run: python main.py